spring:
  dbhost: 192.168.0.64
  database: test
  datasource:
    # url: jdbc:mysql://${dbhost:3306}/${database}
    url: jdbc:mysql://192.168.0.64:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true