spring:
  dbhost: 192.168.0.64
  database: test
  datasource:
    # Spring 2.x
    jdbc-url: jdbc:mysql://192.168.0.64:3306/test
    # Spring 1.5
    # url: jdbc:mysql://192.168.0.64:3306/test
    username: java
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      # update
    show-sql: true
  jackson:
    serialization:
      indent-output: true
