global:
  scrape_interval: 15s
  scrape_timeout: 1s
  evaluation_interval: 15s
scrape_configs:
- job_name: pushgateway
  metrics_path: /metrics
  scheme: http
  honor_labels: true
  static_configs:
  - targets: ['pushgateway:9091']
    labels:
      service: pushgateway
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['localhost:8080', "localhost:8081"]
    labels:
      service: prometheus
