spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    # application expects the database to be present on disk and table created
    url: jdbc:sqlite:${HOME}/Desktop/login.db
  jpa:
    database-platform: example.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: 
        - update
        - validate
    show-sql: true
  session:
    store-type: none

security:
  jwt:
    token:
      secret-key: springBootJwt
      expire-length: 8640000

application:
  version: 0.1.0
  admin: admin@admin.com
  develop-mode: false
