---
services: 
  - microservice:
      name: db
      image: mysql
  - microservice: { name: web, image: apache }
  - microservice:
      name: lb
      image: nginx
      depends_on:
        - web
        - db 
        
extradata:
  windows: c:\windows\system32
  linux: /home
settings:
  boolean_setting: true
  integer_setting: 42
  string_setting: somethings

version: 1.0	
