services: 
  - microservice:
      name: db
      image: mysql
  - microservice:      
      name: web
      image: apache

settings:
  boolean_setting: true
  integer_setting: 42
  string_setting: somethings

version: 1.0	
