version: '3.7'
services:
  app:
    container_name: example-mongo
    environment:
      SERVICE_PORT: 27017
      SERVICE_HOST: 'mongo-service'
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #  - /home/$USER/Desktop:/var/properties
    ports:
      - 8085:8085
    working_dir: '/'
    restart: always
    tty: true
    networks:
      - myapp
    depends_on:
      - mongo
  mongo:
    hostname: mongo-service
    container_name: mongo-service
    image: mvertes/alpine-mongo
    networks:
      - myapp
networks:
  myapp:
    driver: bridge
