version: '3.3'
services:
  python_runner:
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
       - ./temp:/temp 
    container_name: python_runner_container 
    environment:
      - FILENAME=${FILENAME}
