version: '2.2'

services:
  app6:
    restart: unless-stopped
    build: app6
    container_name: app6
    environment:
      - MONITOR=true
      - APM_SERVER=apm-server
      - PORT=3000
    ports:
      - "3000:3000"
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:3000/
    depends_on:
      apm-server:
        condition: service_healthy
    networks:
      - elastic
networks:
  elastic:
