version: '2.2'

services:
  app4:
    restart: unless-stopped
    build: app4
    container_name: app4
    environment:
      - MONITOR=true
      - APM_SERVER=apm-server
      - SOAP_SERVER=soap-server
      - PORT=8000
    ports:
      - "8000:8000"
        # NOTE: reporting unhealthy, shows no data in 'Observability'  
        # Commenting healthcheck
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8000/
    depends_on:
      apm-server:
        condition: service_healthy
      soap-server:
        condition: service_healthy
    networks:
      - elastic

  soap-server:
    restart: unless-stopped
    build: app5
    container_name: soap-server
    # NOTE: currently unused, trouble with seeing it from Dockerfile
    environment:
      - APM_SERVER=apm-server
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8888/CurrencyConversionWebService/?wsdl | grep -q 200",
        ]
      interval: 10s
      timeout: 10s
      retries: 60
        
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "8888:8888"
    networks:
      - elastic

networks:
  elastic:
