scrape_configs:
  - job_name: 'application'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

    static_configs:
      - targets: ['application:8443']
        labels:
          group: 'application'

