server:
  port: 8080
  context-path: /springboot

# SQLite Connection

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    # will create table
    url: 'jdbc:sqlite::memory:'
#    url: jdbc:sqlite:${HOME}/Desktop/springboot.db
  jpa:
    database-platform: example.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
