scrape_configs:
  - job_name:       'application'

    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

    static_configs:
      - targets: ['application:8080']
        labels:
          group: 'application'

