version: '2'
services:
  jm-app:
    image: app
    ports:
    - "8080:8080"
    depends_on:
    - jm-postgres
  jm-postgres:
    image: postgres:10.1
    ports:
     - "5431:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb


