version: '2.1'

services:
  consul:
    command: -server -bootstrap -advertise 192.168.99.100
    image: progrium/consul:latest
    hostname: 127.0.0.1.xip.io
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  portafolio_test:
    image: test/portafolio
    ports:
      - "57116:57116"
    environment:
      CONSUL_HOST: consul
      DISCOVERY_ENABLED: "true"
    depends_on:
      - consul
    links:
      - consul
  pricing_test:
    image: test/pricing

    ports:
      - "57216:57216"
    environment:
      CONSUL_HOST: consul
      DISCOVERY_ENABLED: "true"
    depends_on:
      - consul
      - portafolio_test
    links:
      - consul
      - portafolio_test
