spring:
  application:
    name: portfolio-service
  cloud:
    consul:
#      setting directly has no effect 
#      host: consul-microservice-discovery-sample_consul_1
      host: ${CONSUL_HOST}
      port: 8500

server:
  port: 57116
