---
property1: {{* name1|||https://www.application-dev.com:8080/some_path *}} # NOTE: comment will get wiped
property2: {{*name2|||default2*}}
property3: {{*  name3|||default3   *}}
property4: {{*name4|||default4*}}    # comment
# comment
property5: value5
# missing from properties - will be replaced with default
property6: {{*  name6|||default6*}} # comment
property7: {{*name7|||default7 *}}
