# https://github.com/mminks/haproxy-docker-logging/blob/master/docker-compose.yml
version: "3.7"
services:
  haproxy:
    build:
      context: .
    ports:
      - 8080:9000
    volumes:
      - ./haproxy.cfg.EXAMPLE:/usr/local/etc/haproxy/haproxy.cfg
