http: 
  port: 8080
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/basic.p12
    key-store-password: password
    key-alias: basic


trust:
  store: classpath:keystore/basic.p12
    password: password
    # org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here  
    # challenge with defining 'trust.store' and 'trust.store.password' in the same coniguration
    # also spotted by yamllint / optimist:
    # mapping values are not allowed in this context at line 15 column 13
    # YAML lint found 1 errors
test:
  username: admin
  password: password

