server:
  port: 8085
  context-path: /
# SQLite connection commented
# MySQL connection details active
spring:
  session:
     store-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/test'
    username: java
    password: password
  jpa:
    database-platform:  org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
