version: "3"
services:
  apm-elasticsearch:
    image: blacktop/elasticsearch:7.1
    ports:
    - 9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    environment:
      ELASTICSEARCH_URL: http://apm-elasticsearch:9200
    ports:
    - 5601:5601
    links:
    - apm-elasticsearch
    depends_on:
    - apm-elasticsearch
  elastic-apm-server:
    image: docker.elastic.co/apm/apm-server:7.1.0
    command: [
      "bash",
      "-c",
      "apm-server run -e -E
                          output.elasticsearch.hosts=['http://apm-elasticsearch:9200']
                          "]
    ports:
    - 8200
    links:
    - apm-elasticsearch
    depends_on:
    - apm-elasticsearch
  app-server:
    image: openjdk:8-jre-alpine3.9
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
      - JAR_FILE=target/example.static_page.jar
    ports:
    - 8080:8080
    environment:
      ELASTIC_APM_SERVICE_NAME: app-server
      ELASTIC_APM_APPLICATION_PACKAGES: example.static_page
      ELASTIC_APM_SERVER_URLS: http://elastic-apm-server:8200
    links:
    - elastic-apm-server
    depends_on:
    - elastic-apm-server
