---
- hosts: localhost
  tasks:
    - docker_container:
        name: example-play
        image: python:2.7.17-alpine3.9 # python:alpine
        command: ["sleep", "1d"]

- name: Example play
  hosts: example-play
  roles:
    - name: "docker-role"
