version: '2.2'

services:
  soap-server:
    restart: unless-stopped
    build: ./server
    container_name: soap-server
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl -s -X GET http://localhost:9999/service/hello-world?wsdl",
        ]
      interval: 10s
      timeout: 10s
      retries: 60
        
    ports:
      - "9999:9999"
      - "9000:9000"
    networks:
      - soap

  soap-client:
    restart: unless-stopped
    build: ./client
    container_name: soap-client
    ports:
      - "8080:80" 
    depends_on:
      soap-server:
        condition: service_healthy
    networks:
      - soap
#   healthcheck:
#     test:
#       [
#           "CMD-SHELL",
#           "curl http://localhost:5601/api/status | grep -q '401'",
#       ]
#     interval: 10s
#     timeout: 10s
#     retries: 120
networks:
  soap:
