---
version: '3.6'
services:
  client:
    restart: unless-stopped
    build: client
    container_name: client
    ports:
      - "5000:5000" 
    depends_on:
      soap-server:
        condition: service_healthy
    environment:
      - SERVER=soap-server
    networks:
      - example
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://127.0.0.1:5000/ | grep -q 200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  example:
    restart: unless-stopped
    build: client
    container_name: client
    ports:
      - "5000:5000" 
    depends_on:
      # NOTE: the `depends_on` may not be working correctly under docker-compose-with-extends.yml
      soap-server:
        condition: service_healthy
    environment:
      - SERVER=soap-server
    networks:
      - example
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://127.0.0.1:5000/ | grep -q 200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  example:
