version: '2'

services:
  mysql_db:
    # container_name: mysql_db
    image: mysql:8.0.18
    # NODE: it probably isn't worth risk to use 'latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=nimda'
      - 'MYSQL_USER=example_db_user'
      - 'MYSQL_DATABASE=example_db'
      - 'MYSQL_PASSWORD=example_db_pass'
  #  ports:
  #    - "3306:3306"
    volumes:
     - ./db:/docker-entrypoint-initdb.d
  
  wait-for-dependencies:
    # container_name: wait-for-dependencies
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql_db
    networks:
      - example
    command: mysql_db:3306 
    # NOTE: docker dns not working:
    # nc: bad address 'mysql_db'
    networks:
      - example
  web:
    # image: tomcat:latest
    image: tomcat:8.0-alpine
    # TODO: poor synchronization: 
    # Environment variables do not get loaded during first launch of catalina
    depends_on:
      - wait-for-dependencies
    networks:
      - example
    environment:
      - 'JDBC_URL=jdbc:mysql://mysql_db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true'
      - 'JDBC_USER=example_db_user'
      - 'JDBC_PASS=example_db_pass'
    ports:
     - "80:8080"
    volumes:
     - ./tomcat/webapps:/usr/local/tomcat/webapps
    links:
      - mysql_db
    networks:
      - example
networks:
  example:
