version: '3.5'

services:
  mysql-server:
    container_name: mysql-server
    hostname: mysql-server
    image: mysql:5.7
    # NOTE: myslq:8 jdbc requires java 8+ thus conflicts with tomcat:8.0-alpine
    # that has java 7
    environment:
      - 'MYSQL_ROOT_PASSWORD=nimda'
      - 'MYSQL_USER=example_db_user'
      - 'MYSQL_DATABASE=example_db'
      - 'MYSQL_PASSWORD=example_db_pass'
    ports:
      - "3306:3306"
    volumes:
     - ./db:/docker-entrypoint-initdb.d
    networks:
      - example
  delayed_start:
    container_name: delayed_start
    build:
      context: .
      dockerfile: Dockerfile.delayed_start
    image: alpine:3.9
    depends_on:
      - mysql-server
    environment:
      SERVICE_PORT: 3306
      SERVICE_HOST: mysql-server
      # NOTE - Docker dns hostname: setting in the dependency container
    networks:
      - example
  web:
    image: tomcat:8.0-alpine
    # NOTE: has java 7
    # image: davidcaste/alpine-tomcat:jre8tomcat8
    # TODO: poor synchronization: 
    # Environment variables aren't loaded during first launch of catalina
    depends_on:
      - delayed_start
      - mysql-server
    networks:
      - example
    environment:
      - 'JDBC_URL=jdbc:mysql://mysql-server:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true'
      - 'JDBC_USER=example_db_user'
      - 'JDBC_PASS=example_db_pass'
    ports:
     - "80:8080"
    volumes:
     - ./tomcat/webapps:/usr/local/tomcat/webapps
    links:
      - mysql-server
networks:
  example:
