apiVersion: apps/v1
kind: Deployment
metadata:
  name: perl-app
spec:
  selector:
    matchLabels:
      app: perl-app
  replicas: 1
  template:
    metadata:
      labels:
        app: perl-app
    spec:
      containers:
      - name: perl-app
        image: basic-perl-cgi 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
