version: '3.5'
services:
  prometheus:
    image: prom/prometheus:v2.27.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - ./recording-rules.yml:/etc/prometheus/recording-rules.yml:Z
  metrics:
    build:
      context: .
      dockerfile: Dockerfile.node-exporter
      # NOTE: when both present, 'image' may ovrride
    # image: prom/node-exporter:v1.3.1
    ports: 
      - "9100:9100"
#    volumes:
#      - ./static-metrics.prom:/var/metrics/metrics.prom:Z
#  node-exporter:
#    image: prom/node-exporter
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command: 
#      - '--path.procfs=/host/proc' 
#      - '--path.sysfs=/host/sys'
#      - --collector.filesystem.ignored-mount-points
#      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
#    ports:
#      - "9100:9100"
#    privileged: true
#    restart: always
