apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true
  kibana:
    enabled: true
    host: "kibana:5601"
    protocol: "http"
#    username: "elastic"
#    password: "elasticpassword"
# NOTE: 'setup.template' was removed from `apm-server.yml` in 8.0: index templates are managed by Fleet
# NOTE: in 7.x but not in 8.x also one can configure 'output.elasticsearch.index'
setup.template.enabled: true
#setup.template.name: "apm-%{[observer.version]}"
#setup.template.pattern: "apm-%{[observer.version]}-*"
setup.template.fields: "${path.config}/fields.yml"
setup.template.overwrite: true

setup.template.append_fields:
  - name: http.request.headers
    type: object
  - name: http.request.headers.Appendedfield
    type: keyword
 
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "http"
  pipeline: apm
  #  username: elastic
  #  password: elasticpassword
#  index: "apm-%{[observer.version]}-%{+yyyy.MM.dd}"
#  indices:
#    - index: "apm-%{[observer.version]}-sourcemap"
#      when.contains:
#        processor.event: "sourcemap"
#    - index: "apm-%{[observer.version]}-error-%{+yyyy.MM.dd}"
#      when.contains:
#        processor.event: "error"
#    - index: "apm-%{[observer.version]}-transaction-%{+yyyy.MM.dd}"
#      when.contains:
#        processor.event: "transaction"
#    - index: "apm-%{[observer.version]}-span-%{+yyyy.MM.dd}"
#      when.contains:
#        processor.event: "span"
#    - index: "apm-%{[observer.version]}-metric-%{+yyyy.MM.dd}"
#      when.contains:
#        processor.event: "metric"
#    - index: "apm-%{[observer.version]}-onboarding-%{+yyyy.MM.dd}"
#      when.contains:
#        processor.event: "onboarding"

monitoring.enabled: true
monitoring.elasticsearch:
  # username: "elastic"
  #  password: "elasticpassword"
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: 'kibana:5601'


#logging:
#  to_files: false
