cluster.name: "docker-cluster" 
network.host: 0.0.0.0 

xpack.license.self_generated.type: basic
#xpack.security.authc.token.enable: true
#xpack.security.authc.api_key.enabled: true

xpack.security.enabled: false
xpack.monitoring.collection.enabled: true
